apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatunnel-web-api
  namespace: seatunnel-web
  labels:
    app: seatunnel-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatunnel-web-api
  template:
    metadata:
      labels:
        app: seatunnel-web-api
    spec:
      containers:
        - name: seatunnel-web-api
          image: harbor.example.com/data/seatunnel-web-api:starrocks-test
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9527
          env:
            - name: SERVER_PORT
              value: "9527"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /seatunnel-web-api
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: seatunnel-web-api-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: seatunnel-web-api-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: seatunnel-web-db
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seatunnel-web-db
                  key: password

