apiVersion: v1
kind: Service
metadata:
  name: seatunnel-web-ui
  namespace: seatunnel-web
  labels:
    app: seatunnel-web-ui
spec:
  type: ClusterIP
  selector:
    app: seatunnel-web-ui
  ports:
    - name: http
      port: 80
      targetPort: 80

